// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActivityUnlockCriterion
    {
        [DataMember(Name = "stat")]
        public StatType Stat;
        [DataMember(Name = "min_value")]
        public int MinValue;

        public ActivityUnlockCriterion(
            StatType Stat,
            int MinValue
        )
        {
            this.Stat = Stat;
            this.MinValue = MinValue;
        }

        public ActivityUnlockCriterion()
        {
        }
    }
}
