// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Activity
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "participant")]
        public SpacetimeDB.Identity Participant;
        [DataMember(Name = "type")]
        public ActivityType Type;
        [DataMember(Name = "cost")]
        public System.Collections.Generic.List<ActivityCost> Cost;
        [DataMember(Name = "duration_ms")]
        public ulong DurationMs;
        [DataMember(Name = "required_location")]
        public LocationType? RequiredLocation;
        [DataMember(Name = "unlock_criteria")]
        public System.Collections.Generic.List<ActivityUnlockCriterion> UnlockCriteria;
        [DataMember(Name = "level")]
        public uint Level;

        public Activity(
            ulong Id,
            SpacetimeDB.Identity Participant,
            ActivityType Type,
            System.Collections.Generic.List<ActivityCost> Cost,
            ulong DurationMs,
            LocationType? RequiredLocation,
            System.Collections.Generic.List<ActivityUnlockCriterion> UnlockCriteria,
            uint Level
        )
        {
            this.Id = Id;
            this.Participant = Participant;
            this.Type = Type;
            this.Cost = Cost;
            this.DurationMs = DurationMs;
            this.RequiredLocation = RequiredLocation;
            this.UnlockCriteria = UnlockCriteria;
            this.Level = Level;
        }

        public Activity()
        {
            this.Cost = new();
            this.UnlockCriteria = new();
        }
    }
}
