// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActivitySchedule
    {
        [DataMember(Name = "schedule_id")]
        public ulong ScheduleId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "type")]
        public ActivityType Type;
        [DataMember(Name = "interval_milliseconds")]
        public ulong? IntervalMilliseconds;
        [DataMember(Name = "participant")]
        public SpacetimeDB.Identity Participant;

        public ActivitySchedule(
            ulong ScheduleId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            ActivityType Type,
            ulong? IntervalMilliseconds,
            SpacetimeDB.Identity Participant
        )
        {
            this.ScheduleId = ScheduleId;
            this.ScheduledAt = ScheduledAt;
            this.Type = Type;
            this.IntervalMilliseconds = IntervalMilliseconds;
            this.Participant = Participant;
        }

        public ActivitySchedule()
        {
            this.ScheduledAt = null!;
        }
    }
}
