// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActiveTask
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "participant")]
        public SpacetimeDB.Identity Participant;
        [DataMember(Name = "type")]
        public ActivityType Type;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;
        [DataMember(Name = "completes_at")]
        public SpacetimeDB.Timestamp CompletesAt;

        public ActiveTask(
            ulong Id,
            SpacetimeDB.Identity Participant,
            ActivityType Type,
            SpacetimeDB.Timestamp StartedAt,
            SpacetimeDB.Timestamp CompletesAt
        )
        {
            this.Id = Id;
            this.Participant = Participant;
            this.Type = Type;
            this.StartedAt = StartedAt;
            this.CompletesAt = CompletesAt;
        }

        public ActiveTask()
        {
        }
    }
}
