// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GuildResourceTracker
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "guild_id")]
        public ulong GuildId;
        [DataMember(Name = "type")]
        public ResourceType Type;
        [DataMember(Name = "amount")]
        public ulong Amount;

        public GuildResourceTracker(
            ulong Id,
            ulong GuildId,
            ResourceType Type,
            ulong Amount
        )
        {
            this.Id = Id;
            this.GuildId = GuildId;
            this.Type = Type;
            this.Amount = Amount;
        }

        public GuildResourceTracker()
        {
        }
    }
}
