// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Guild
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "founder_id")]
        public SpacetimeDB.Identity FounderId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Guild(
            ulong Id,
            SpacetimeDB.Identity FounderId,
            string Name,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.FounderId = FounderId;
            this.Name = Name;
            this.CreatedAt = CreatedAt;
        }

        public Guild()
        {
            this.Name = "";
        }
    }
}
