// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GuildInvite
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "guild_id")]
        public ulong GuildId;
        [DataMember(Name = "inviter_id")]
        public SpacetimeDB.Identity InviterId;
        [DataMember(Name = "invitee_id")]
        public SpacetimeDB.Identity InviteeId;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public GuildInvite(
            ulong Id,
            ulong GuildId,
            SpacetimeDB.Identity InviterId,
            SpacetimeDB.Identity InviteeId,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.GuildId = GuildId;
            this.InviterId = InviterId;
            this.InviteeId = InviteeId;
            this.CreatedAt = CreatedAt;
        }

        public GuildInvite()
        {
        }
    }
}
