// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GuildJoinRequest
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "guild_id")]
        public ulong GuildId;
        [DataMember(Name = "requester_id")]
        public SpacetimeDB.Identity RequesterId;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public GuildJoinRequest(
            ulong Id,
            ulong GuildId,
            SpacetimeDB.Identity RequesterId,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.GuildId = GuildId;
            this.RequesterId = RequesterId;
            this.CreatedAt = CreatedAt;
        }

        public GuildJoinRequest()
        {
        }
    }
}
