// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GuildMember
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "guild_id")]
        public ulong GuildId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "role")]
        public GuildRole Role;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;

        public GuildMember(
            ulong Id,
            ulong GuildId,
            SpacetimeDB.Identity PlayerId,
            GuildRole Role,
            SpacetimeDB.Timestamp JoinedAt
        )
        {
            this.Id = Id;
            this.GuildId = GuildId;
            this.PlayerId = PlayerId;
            this.Role = Role;
            this.JoinedAt = JoinedAt;
        }

        public GuildMember()
        {
        }
    }
}
