// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStat
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "stat")]
        public StatType Stat;
        [DataMember(Name = "value")]
        public int Value;

        public PlayerStat(
            ulong Id,
            SpacetimeDB.Identity Owner,
            StatType Stat,
            int Value
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.Stat = Stat;
            this.Value = Value;
        }

        public PlayerStat()
        {
        }
    }
}
