// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStructure
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "definition_id")]
        public ulong DefinitionId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "built_at")]
        public SpacetimeDB.Timestamp BuiltAt;

        public PlayerStructure(
            ulong Id,
            SpacetimeDB.Identity Owner,
            ulong DefinitionId,
            uint Level,
            SpacetimeDB.Timestamp BuiltAt
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.DefinitionId = DefinitionId;
            this.Level = Level;
            this.BuiltAt = BuiltAt;
        }

        public PlayerStructure()
        {
        }
    }
}
