// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "email")]
        public string? Email;
        [DataMember(Name = "online")]
        public bool Online;

        public Player(
            SpacetimeDB.Identity Identity,
            string DisplayName,
            string? Email,
            bool Online
        )
        {
            this.Identity = Identity;
            this.DisplayName = DisplayName;
            this.Email = Email;
            this.Online = Online;
        }

        public Player()
        {
            this.DisplayName = "";
        }
    }
}
