// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerShelter
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "level")]
        public byte Level;
        [DataMember(Name = "built_at")]
        public SpacetimeDB.Timestamp BuiltAt;

        public PlayerShelter(
            SpacetimeDB.Identity Owner,
            byte Level,
            SpacetimeDB.Timestamp BuiltAt
        )
        {
            this.Owner = Owner;
            this.Level = Level;
            this.BuiltAt = BuiltAt;
        }

        public PlayerShelter()
        {
        }
    }
}
