// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResourceTracker
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "type")]
        public ResourceType Type;
        [DataMember(Name = "amount")]
        public ulong Amount;

        public ResourceTracker(
            ulong Id,
            SpacetimeDB.Identity Owner,
            ResourceType Type,
            ulong Amount
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.Type = Type;
            this.Amount = Amount;
        }

        public ResourceTracker()
        {
        }
    }
}
