// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StructureDefinition
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "cost")]
        public System.Collections.Generic.List<ActivityCost> Cost;

        public StructureDefinition(
            ulong Id,
            string Name,
            System.Collections.Generic.List<ActivityCost> Cost
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Cost = Cost;
        }

        public StructureDefinition()
        {
            this.Name = "";
            this.Cost = new();
        }
    }
}
