// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StructureModifier
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_structure_id")]
        public ulong PlayerStructureId;
        [DataMember(Name = "modifier_name")]
        public string ModifierName;
        [DataMember(Name = "value")]
        public int Value;

        public StructureModifier(
            ulong Id,
            ulong PlayerStructureId,
            string ModifierName,
            int Value
        )
        {
            this.Id = Id;
            this.PlayerStructureId = PlayerStructureId;
            this.ModifierName = ModifierName;
            this.Value = Value;
        }

        public StructureModifier()
        {
            this.ModifierName = "";
        }
    }
}
