// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TaskCompletion
    {
        [DataMember(Name = "schedule_id")]
        public ulong ScheduleId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "participant")]
        public SpacetimeDB.Identity Participant;
        [DataMember(Name = "type")]
        public ActivityType Type;

        public TaskCompletion(
            ulong ScheduleId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            SpacetimeDB.Identity Participant,
            ActivityType Type
        )
        {
            this.ScheduleId = ScheduleId;
            this.ScheduledAt = ScheduledAt;
            this.Participant = Participant;
            this.Type = Type;
        }

        public TaskCompletion()
        {
            this.ScheduledAt = null!;
        }
    }
}
