// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AcceptJoinRequestHandler(ReducerEventContext ctx, ulong requestId);
        public event AcceptJoinRequestHandler? OnAcceptJoinRequest;

        public void AcceptJoinRequest(ulong requestId)
        {
            conn.InternalCallReducer(new Reducer.AcceptJoinRequest(requestId));
        }

        public bool InvokeAcceptJoinRequest(ReducerEventContext ctx, Reducer.AcceptJoinRequest args)
        {
            if (OnAcceptJoinRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAcceptJoinRequest(
                ctx,
                args.RequestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AcceptJoinRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;

            public AcceptJoinRequest(ulong RequestId)
            {
                this.RequestId = RequestId;
            }

            public AcceptJoinRequest()
            {
            }

            string IReducerArgs.ReducerName => "accept_join_request";
        }
    }
}
