// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActivityOnIntervalHandler(ReducerEventContext ctx, SpacetimeDB.Identity participant, SpacetimeDB.Types.ActivityType type, ulong interval, bool reoccuring);
        public event ActivityOnIntervalHandler? OnActivityOnInterval;

        public void ActivityOnInterval(SpacetimeDB.Identity participant, SpacetimeDB.Types.ActivityType type, ulong interval, bool reoccuring)
        {
            conn.InternalCallReducer(new Reducer.ActivityOnInterval(participant, type, interval, reoccuring));
        }

        public bool InvokeActivityOnInterval(ReducerEventContext ctx, Reducer.ActivityOnInterval args)
        {
            if (OnActivityOnInterval == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnActivityOnInterval(
                ctx,
                args.Participant,
                args.Type,
                args.Interval,
                args.Reoccuring
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActivityOnInterval : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant")]
            public SpacetimeDB.Identity Participant;
            [DataMember(Name = "type")]
            public ActivityType Type;
            [DataMember(Name = "interval")]
            public ulong Interval;
            [DataMember(Name = "reoccuring")]
            public bool Reoccuring;

            public ActivityOnInterval(
                SpacetimeDB.Identity Participant,
                ActivityType Type,
                ulong Interval,
                bool Reoccuring
            )
            {
                this.Participant = Participant;
                this.Type = Type;
                this.Interval = Interval;
                this.Reoccuring = Reoccuring;
            }

            public ActivityOnInterval()
            {
            }

            string IReducerArgs.ReducerName => "activity_on_interval";
        }
    }
}
