// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddResourceToPlayerHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerId, SpacetimeDB.Types.ResourceType type, ulong amount);
        public event AddResourceToPlayerHandler? OnAddResourceToPlayer;

        public void AddResourceToPlayer(SpacetimeDB.Identity playerId, SpacetimeDB.Types.ResourceType type, ulong amount)
        {
            conn.InternalCallReducer(new Reducer.AddResourceToPlayer(playerId, type, amount));
        }

        public bool InvokeAddResourceToPlayer(ReducerEventContext ctx, Reducer.AddResourceToPlayer args)
        {
            if (OnAddResourceToPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddResourceToPlayer(
                ctx,
                args.PlayerId,
                args.Type,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddResourceToPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public SpacetimeDB.Identity PlayerId;
            [DataMember(Name = "type")]
            public ResourceType Type;
            [DataMember(Name = "amount")]
            public ulong Amount;

            public AddResourceToPlayer(
                SpacetimeDB.Identity PlayerId,
                ResourceType Type,
                ulong Amount
            )
            {
                this.PlayerId = PlayerId;
                this.Type = Type;
                this.Amount = Amount;
            }

            public AddResourceToPlayer()
            {
            }

            string IReducerArgs.ReducerName => "add_resource_to_player";
        }
    }
}
