// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddResourceToPlayerByPlayerNameHandler(ReducerEventContext ctx, string name, string resourceType, ulong amount);
        public event AddResourceToPlayerByPlayerNameHandler? OnAddResourceToPlayerByPlayerName;

        public void AddResourceToPlayerByPlayerName(string name, string resourceType, ulong amount)
        {
            conn.InternalCallReducer(new Reducer.AddResourceToPlayerByPlayerName(name, resourceType, amount));
        }

        public bool InvokeAddResourceToPlayerByPlayerName(ReducerEventContext ctx, Reducer.AddResourceToPlayerByPlayerName args)
        {
            if (OnAddResourceToPlayerByPlayerName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddResourceToPlayerByPlayerName(
                ctx,
                args.Name,
                args.ResourceType,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddResourceToPlayerByPlayerName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "resource_type")]
            public string ResourceType;
            [DataMember(Name = "amount")]
            public ulong Amount;

            public AddResourceToPlayerByPlayerName(
                string Name,
                string ResourceType,
                ulong Amount
            )
            {
                this.Name = Name;
                this.ResourceType = ResourceType;
                this.Amount = Amount;
            }

            public AddResourceToPlayerByPlayerName()
            {
                this.Name = "";
                this.ResourceType = "";
            }

            string IReducerArgs.ReducerName => "add_resource_to_player_by_player_name";
        }
    }
}
