// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BuildStructureHandler(ReducerEventContext ctx, ulong definitionId);
        public event BuildStructureHandler? OnBuildStructure;

        public void BuildStructure(ulong definitionId)
        {
            conn.InternalCallReducer(new Reducer.BuildStructure(definitionId));
        }

        public bool InvokeBuildStructure(ReducerEventContext ctx, Reducer.BuildStructure args)
        {
            if (OnBuildStructure == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBuildStructure(
                ctx,
                args.DefinitionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BuildStructure : Reducer, IReducerArgs
        {
            [DataMember(Name = "definition_id")]
            public ulong DefinitionId;

            public BuildStructure(ulong DefinitionId)
            {
                this.DefinitionId = DefinitionId;
            }

            public BuildStructure()
            {
            }

            string IReducerArgs.ReducerName => "build_structure";
        }
    }
}
