// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CancelJoinRequestHandler(ReducerEventContext ctx);
        public event CancelJoinRequestHandler? OnCancelJoinRequest;

        public void CancelJoinRequest()
        {
            conn.InternalCallReducer(new Reducer.CancelJoinRequest());
        }

        public bool InvokeCancelJoinRequest(ReducerEventContext ctx, Reducer.CancelJoinRequest args)
        {
            if (OnCancelJoinRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCancelJoinRequest(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CancelJoinRequest : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "cancel_join_request";
        }
    }
}
