// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DisbandGuildHandler(ReducerEventContext ctx);
        public event DisbandGuildHandler? OnDisbandGuild;

        public void DisbandGuild()
        {
            conn.InternalCallReducer(new Reducer.DisbandGuild());
        }

        public bool InvokeDisbandGuild(ReducerEventContext ctx, Reducer.DisbandGuild args)
        {
            if (OnDisbandGuild == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDisbandGuild(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DisbandGuild : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "disband_guild";
        }
    }
}
