// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InviteToGuildHandler(ReducerEventContext ctx, SpacetimeDB.Identity inviteeId);
        public event InviteToGuildHandler? OnInviteToGuild;

        public void InviteToGuild(SpacetimeDB.Identity inviteeId)
        {
            conn.InternalCallReducer(new Reducer.InviteToGuild(inviteeId));
        }

        public bool InvokeInviteToGuild(ReducerEventContext ctx, Reducer.InviteToGuild args)
        {
            if (OnInviteToGuild == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInviteToGuild(
                ctx,
                args.InviteeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InviteToGuild : Reducer, IReducerArgs
        {
            [DataMember(Name = "invitee_id")]
            public SpacetimeDB.Identity InviteeId;

            public InviteToGuild(SpacetimeDB.Identity InviteeId)
            {
                this.InviteeId = InviteeId;
            }

            public InviteToGuild()
            {
            }

            string IReducerArgs.ReducerName => "invite_to_guild";
        }
    }
}
