// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinGuildHandler(ReducerEventContext ctx, ulong inviteId);
        public event JoinGuildHandler? OnJoinGuild;

        public void JoinGuild(ulong inviteId)
        {
            conn.InternalCallReducer(new Reducer.JoinGuild(inviteId));
        }

        public bool InvokeJoinGuild(ReducerEventContext ctx, Reducer.JoinGuild args)
        {
            if (OnJoinGuild == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinGuild(
                ctx,
                args.InviteId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinGuild : Reducer, IReducerArgs
        {
            [DataMember(Name = "invite_id")]
            public ulong InviteId;

            public JoinGuild(ulong InviteId)
            {
                this.InviteId = InviteId;
            }

            public JoinGuild()
            {
            }

            string IReducerArgs.ReducerName => "join_guild";
        }
    }
}
