// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void KickMemberHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerId);
        public event KickMemberHandler? OnKickMember;

        public void KickMember(SpacetimeDB.Identity playerId)
        {
            conn.InternalCallReducer(new Reducer.KickMember(playerId));
        }

        public bool InvokeKickMember(ReducerEventContext ctx, Reducer.KickMember args)
        {
            if (OnKickMember == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnKickMember(
                ctx,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class KickMember : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public SpacetimeDB.Identity PlayerId;

            public KickMember(SpacetimeDB.Identity PlayerId)
            {
                this.PlayerId = PlayerId;
            }

            public KickMember()
            {
            }

            string IReducerArgs.ReducerName => "kick_member";
        }
    }
}
