// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootBigWoodHandler(ReducerEventContext ctx, SpacetimeDB.Identity participant);
        public event LootBigWoodHandler? OnLootBigWood;

        public void LootBigWood(SpacetimeDB.Identity participant)
        {
            conn.InternalCallReducer(new Reducer.LootBigWood(participant));
        }

        public bool InvokeLootBigWood(ReducerEventContext ctx, Reducer.LootBigWood args)
        {
            if (OnLootBigWood == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootBigWood(
                ctx,
                args.Participant
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootBigWood : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant")]
            public SpacetimeDB.Identity Participant;

            public LootBigWood(SpacetimeDB.Identity Participant)
            {
                this.Participant = Participant;
            }

            public LootBigWood()
            {
            }

            string IReducerArgs.ReducerName => "loot_big_wood";
        }
    }
}
