// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveAllScheduledEventsForParticipantHandler(ReducerEventContext ctx, SpacetimeDB.Identity participant);
        public event RemoveAllScheduledEventsForParticipantHandler? OnRemoveAllScheduledEventsForParticipant;

        public void RemoveAllScheduledEventsForParticipant(SpacetimeDB.Identity participant)
        {
            conn.InternalCallReducer(new Reducer.RemoveAllScheduledEventsForParticipant(participant));
        }

        public bool InvokeRemoveAllScheduledEventsForParticipant(ReducerEventContext ctx, Reducer.RemoveAllScheduledEventsForParticipant args)
        {
            if (OnRemoveAllScheduledEventsForParticipant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveAllScheduledEventsForParticipant(
                ctx,
                args.Participant
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveAllScheduledEventsForParticipant : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant")]
            public SpacetimeDB.Identity Participant;

            public RemoveAllScheduledEventsForParticipant(SpacetimeDB.Identity Participant)
            {
                this.Participant = Participant;
            }

            public RemoveAllScheduledEventsForParticipant()
            {
            }

            string IReducerArgs.ReducerName => "remove_all_scheduled_events_for_participant";
        }
    }
}
