// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ScavengeHandler(ReducerEventContext ctx, SpacetimeDB.Identity participant);
        public event ScavengeHandler? OnScavenge;

        public void Scavenge(SpacetimeDB.Identity participant)
        {
            conn.InternalCallReducer(new Reducer.Scavenge(participant));
        }

        public bool InvokeScavenge(ReducerEventContext ctx, Reducer.Scavenge args)
        {
            if (OnScavenge == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnScavenge(
                ctx,
                args.Participant
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Scavenge : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant")]
            public SpacetimeDB.Identity Participant;

            public Scavenge(SpacetimeDB.Identity Participant)
            {
                this.Participant = Participant;
            }

            public Scavenge()
            {
            }

            string IReducerArgs.ReducerName => "scavenge";
        }
    }
}
