// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartActiveSchedulesHandler(ReducerEventContext ctx, SpacetimeDB.Identity participant);
        public event StartActiveSchedulesHandler? OnStartActiveSchedules;

        public void StartActiveSchedules(SpacetimeDB.Identity participant)
        {
            conn.InternalCallReducer(new Reducer.StartActiveSchedules(participant));
        }

        public bool InvokeStartActiveSchedules(ReducerEventContext ctx, Reducer.StartActiveSchedules args)
        {
            if (OnStartActiveSchedules == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartActiveSchedules(
                ctx,
                args.Participant
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartActiveSchedules : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant")]
            public SpacetimeDB.Identity Participant;

            public StartActiveSchedules(SpacetimeDB.Identity Participant)
            {
                this.Participant = Participant;
            }

            public StartActiveSchedules()
            {
            }

            string IReducerArgs.ReducerName => "start_active_schedules";
        }
    }
}
