// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartActivityHandler(ReducerEventContext ctx, SpacetimeDB.Types.ActivityType type);
        public event StartActivityHandler? OnStartActivity;

        public void StartActivity(SpacetimeDB.Types.ActivityType type)
        {
            conn.InternalCallReducer(new Reducer.StartActivity(type));
        }

        public bool InvokeStartActivity(ReducerEventContext ctx, Reducer.StartActivity args)
        {
            if (OnStartActivity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartActivity(
                ctx,
                args.Type
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartActivity : Reducer, IReducerArgs
        {
            [DataMember(Name = "type")]
            public ActivityType Type;

            public StartActivity(ActivityType Type)
            {
                this.Type = Type;
            }

            public StartActivity()
            {
            }

            string IReducerArgs.ReducerName => "start_activity";
        }
    }
}
