// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpgradeActivityHandler(ReducerEventContext ctx, SpacetimeDB.Types.ActivityType type);
        public event UpgradeActivityHandler? OnUpgradeActivity;

        public void UpgradeActivity(SpacetimeDB.Types.ActivityType type)
        {
            conn.InternalCallReducer(new Reducer.UpgradeActivity(type));
        }

        public bool InvokeUpgradeActivity(ReducerEventContext ctx, Reducer.UpgradeActivity args)
        {
            if (OnUpgradeActivity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpgradeActivity(
                ctx,
                args.Type
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpgradeActivity : Reducer, IReducerArgs
        {
            [DataMember(Name = "type")]
            public ActivityType Type;

            public UpgradeActivity(ActivityType Type)
            {
                this.Type = Type;
            }

            public UpgradeActivity()
            {
            }

            string IReducerArgs.ReducerName => "upgrade_activity";
        }
    }
}
