// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActivityScheduleHandle : RemoteTableHandle<EventContext, ActivitySchedule>
        {
            protected override string RemoteTableName => "activity_schedule";

            public sealed class ParticipantIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ActivitySchedule row) => row.Participant;

                public ParticipantIndex(ActivityScheduleHandle table) : base(table) { }
            }

            public readonly ParticipantIndex Participant;

            public sealed class ScheduleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActivitySchedule row) => row.ScheduleId;

                public ScheduleIdUniqueIndex(ActivityScheduleHandle table) : base(table) { }
            }

            public readonly ScheduleIdUniqueIndex ScheduleId;

            internal ActivityScheduleHandle(DbConnection conn) : base(conn)
            {
                Participant = new(this);
                ScheduleId = new(this);
            }

            protected override object GetPrimaryKey(ActivitySchedule row) => row.ScheduleId;
        }

        public readonly ActivityScheduleHandle ActivitySchedule;
    }

    public sealed class ActivityScheduleCols
    {
        public global::SpacetimeDB.Col<ActivitySchedule, ulong> ScheduleId { get; }
        public global::SpacetimeDB.Col<ActivitySchedule, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<ActivitySchedule, ActivityType> Type { get; }
        public global::SpacetimeDB.Col<ActivitySchedule, ulong> IntervalMilliseconds { get; }
        public global::SpacetimeDB.Col<ActivitySchedule, SpacetimeDB.Identity> Participant { get; }

        public ActivityScheduleCols(string tableName)
        {
            ScheduleId = new global::SpacetimeDB.Col<ActivitySchedule, ulong>(tableName, "schedule_id");
            ScheduledAt = new global::SpacetimeDB.Col<ActivitySchedule, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            Type = new global::SpacetimeDB.Col<ActivitySchedule, ActivityType>(tableName, "type");
            IntervalMilliseconds = new global::SpacetimeDB.Col<ActivitySchedule, ulong>(tableName, "interval_milliseconds");
            Participant = new global::SpacetimeDB.Col<ActivitySchedule, SpacetimeDB.Identity>(tableName, "participant");
        }
    }

    public sealed class ActivityScheduleIxCols
    {
        public global::SpacetimeDB.IxCol<ActivitySchedule, ulong> ScheduleId { get; }
        public global::SpacetimeDB.IxCol<ActivitySchedule, SpacetimeDB.Identity> Participant { get; }

        public ActivityScheduleIxCols(string tableName)
        {
            ScheduleId = new global::SpacetimeDB.IxCol<ActivitySchedule, ulong>(tableName, "schedule_id");
            Participant = new global::SpacetimeDB.IxCol<ActivitySchedule, SpacetimeDB.Identity>(tableName, "participant");
        }
    }
}
