// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActivityHandle : RemoteTableHandle<EventContext, Activity>
        {
            protected override string RemoteTableName => "activity";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Activity row) => row.Id;

                public IdUniqueIndex(ActivityHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ParticipantIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Activity row) => row.Participant;

                public ParticipantIndex(ActivityHandle table) : base(table) { }
            }

            public readonly ParticipantIndex Participant;

            public sealed class ByActivityParticipantTypeIndex : BTreeIndexBase<(SpacetimeDB.Identity Participant, ActivityType Type)>
            {
                protected override (SpacetimeDB.Identity Participant, ActivityType Type) GetKey(Activity row) => (row.Participant, row.Type);

                public ByActivityParticipantTypeIndex(ActivityHandle table) : base(table) { }
            }

            public readonly ByActivityParticipantTypeIndex ByActivityParticipantType;

            internal ActivityHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Participant = new(this);
                ByActivityParticipantType = new(this);
            }

            protected override object GetPrimaryKey(Activity row) => row.Id;
        }

        public readonly ActivityHandle Activity;
    }

    public sealed class ActivityCols
    {
        public global::SpacetimeDB.Col<Activity, ulong> Id { get; }
        public global::SpacetimeDB.Col<Activity, SpacetimeDB.Identity> Participant { get; }
        public global::SpacetimeDB.Col<Activity, ActivityType> Type { get; }
        public global::SpacetimeDB.Col<Activity, System.Collections.Generic.List<ActivityCost>> Cost { get; }
        public global::SpacetimeDB.Col<Activity, ulong> DurationMs { get; }
        public global::SpacetimeDB.Col<Activity, LocationType> RequiredLocation { get; }
        public global::SpacetimeDB.Col<Activity, System.Collections.Generic.List<ActivityUnlockCriterion>> UnlockCriteria { get; }
        public global::SpacetimeDB.Col<Activity, uint> Level { get; }

        public ActivityCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Activity, ulong>(tableName, "id");
            Participant = new global::SpacetimeDB.Col<Activity, SpacetimeDB.Identity>(tableName, "participant");
            Type = new global::SpacetimeDB.Col<Activity, ActivityType>(tableName, "type");
            Cost = new global::SpacetimeDB.Col<Activity, System.Collections.Generic.List<ActivityCost>>(tableName, "cost");
            DurationMs = new global::SpacetimeDB.Col<Activity, ulong>(tableName, "duration_ms");
            RequiredLocation = new global::SpacetimeDB.Col<Activity, LocationType>(tableName, "required_location");
            UnlockCriteria = new global::SpacetimeDB.Col<Activity, System.Collections.Generic.List<ActivityUnlockCriterion>>(tableName, "unlock_criteria");
            Level = new global::SpacetimeDB.Col<Activity, uint>(tableName, "level");
        }
    }

    public sealed class ActivityIxCols
    {
        public global::SpacetimeDB.IxCol<Activity, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Activity, SpacetimeDB.Identity> Participant { get; }
        public global::SpacetimeDB.IxCol<Activity, ActivityType> Type { get; }

        public ActivityIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Activity, ulong>(tableName, "id");
            Participant = new global::SpacetimeDB.IxCol<Activity, SpacetimeDB.Identity>(tableName, "participant");
            Type = new global::SpacetimeDB.IxCol<Activity, ActivityType>(tableName, "type");
        }
    }
}
