// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveTaskHandle : RemoteTableHandle<EventContext, ActiveTask>
        {
            protected override string RemoteTableName => "active_task";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveTask row) => row.Id;

                public IdUniqueIndex(ActiveTaskHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ParticipantUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ActiveTask row) => row.Participant;

                public ParticipantUniqueIndex(ActiveTaskHandle table) : base(table) { }
            }

            public readonly ParticipantUniqueIndex Participant;

            internal ActiveTaskHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Participant = new(this);
            }

            protected override object GetPrimaryKey(ActiveTask row) => row.Id;
        }

        public readonly ActiveTaskHandle ActiveTask;
    }

    public sealed class ActiveTaskCols
    {
        public global::SpacetimeDB.Col<ActiveTask, ulong> Id { get; }
        public global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Identity> Participant { get; }
        public global::SpacetimeDB.Col<ActiveTask, ActivityType> Type { get; }
        public global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Timestamp> StartedAt { get; }
        public global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Timestamp> CompletesAt { get; }

        public ActiveTaskCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ActiveTask, ulong>(tableName, "id");
            Participant = new global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Identity>(tableName, "participant");
            Type = new global::SpacetimeDB.Col<ActiveTask, ActivityType>(tableName, "type");
            StartedAt = new global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Timestamp>(tableName, "started_at");
            CompletesAt = new global::SpacetimeDB.Col<ActiveTask, SpacetimeDB.Timestamp>(tableName, "completes_at");
        }
    }

    public sealed class ActiveTaskIxCols
    {
        public global::SpacetimeDB.IxCol<ActiveTask, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ActiveTask, SpacetimeDB.Identity> Participant { get; }

        public ActiveTaskIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ActiveTask, ulong>(tableName, "id");
            Participant = new global::SpacetimeDB.IxCol<ActiveTask, SpacetimeDB.Identity>(tableName, "participant");
        }
    }
}
