// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GuildMemberHandle : RemoteTableHandle<EventContext, GuildMember>
        {
            protected override string RemoteTableName => "guild_member";

            public sealed class GuildIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GuildMember row) => row.GuildId;

                public GuildIdIndex(GuildMemberHandle table) : base(table) { }
            }

            public readonly GuildIdIndex GuildId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GuildMember row) => row.Id;

                public IdUniqueIndex(GuildMemberHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(GuildMember row) => row.PlayerId;

                public PlayerIdUniqueIndex(GuildMemberHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal GuildMemberHandle(DbConnection conn) : base(conn)
            {
                GuildId = new(this);
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(GuildMember row) => row.Id;
        }

        public readonly GuildMemberHandle GuildMember;
    }

    public sealed class GuildMemberCols
    {
        public global::SpacetimeDB.Col<GuildMember, ulong> Id { get; }
        public global::SpacetimeDB.Col<GuildMember, ulong> GuildId { get; }
        public global::SpacetimeDB.Col<GuildMember, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<GuildMember, GuildRole> Role { get; }
        public global::SpacetimeDB.Col<GuildMember, SpacetimeDB.Timestamp> JoinedAt { get; }

        public GuildMemberCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GuildMember, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.Col<GuildMember, ulong>(tableName, "guild_id");
            PlayerId = new global::SpacetimeDB.Col<GuildMember, SpacetimeDB.Identity>(tableName, "player_id");
            Role = new global::SpacetimeDB.Col<GuildMember, GuildRole>(tableName, "role");
            JoinedAt = new global::SpacetimeDB.Col<GuildMember, SpacetimeDB.Timestamp>(tableName, "joined_at");
        }
    }

    public sealed class GuildMemberIxCols
    {
        public global::SpacetimeDB.IxCol<GuildMember, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GuildMember, ulong> GuildId { get; }
        public global::SpacetimeDB.IxCol<GuildMember, SpacetimeDB.Identity> PlayerId { get; }

        public GuildMemberIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GuildMember, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.IxCol<GuildMember, ulong>(tableName, "guild_id");
            PlayerId = new global::SpacetimeDB.IxCol<GuildMember, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
