// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GuildHandle : RemoteTableHandle<EventContext, Guild>
        {
            protected override string RemoteTableName => "guild";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Guild row) => row.Id;

                public IdUniqueIndex(GuildHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GuildHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Guild row) => row.Id;
        }

        public readonly GuildHandle Guild;
    }

    public sealed class GuildCols
    {
        public global::SpacetimeDB.Col<Guild, ulong> Id { get; }
        public global::SpacetimeDB.Col<Guild, SpacetimeDB.Identity> FounderId { get; }
        public global::SpacetimeDB.Col<Guild, string> Name { get; }
        public global::SpacetimeDB.Col<Guild, SpacetimeDB.Timestamp> CreatedAt { get; }

        public GuildCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Guild, ulong>(tableName, "id");
            FounderId = new global::SpacetimeDB.Col<Guild, SpacetimeDB.Identity>(tableName, "founder_id");
            Name = new global::SpacetimeDB.Col<Guild, string>(tableName, "name");
            CreatedAt = new global::SpacetimeDB.Col<Guild, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class GuildIxCols
    {
        public global::SpacetimeDB.IxCol<Guild, ulong> Id { get; }

        public GuildIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Guild, ulong>(tableName, "id");
        }
    }
}
