// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GuildInviteHandle : RemoteTableHandle<EventContext, GuildInvite>
        {
            protected override string RemoteTableName => "guild_invite";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GuildInvite row) => row.Id;

                public IdUniqueIndex(GuildInviteHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class InviteeIdIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(GuildInvite row) => row.InviteeId;

                public InviteeIdIndex(GuildInviteHandle table) : base(table) { }
            }

            public readonly InviteeIdIndex InviteeId;

            internal GuildInviteHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                InviteeId = new(this);
            }

            protected override object GetPrimaryKey(GuildInvite row) => row.Id;
        }

        public readonly GuildInviteHandle GuildInvite;
    }

    public sealed class GuildInviteCols
    {
        public global::SpacetimeDB.Col<GuildInvite, ulong> Id { get; }
        public global::SpacetimeDB.Col<GuildInvite, ulong> GuildId { get; }
        public global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Identity> InviterId { get; }
        public global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Identity> InviteeId { get; }
        public global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Timestamp> CreatedAt { get; }

        public GuildInviteCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GuildInvite, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.Col<GuildInvite, ulong>(tableName, "guild_id");
            InviterId = new global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Identity>(tableName, "inviter_id");
            InviteeId = new global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Identity>(tableName, "invitee_id");
            CreatedAt = new global::SpacetimeDB.Col<GuildInvite, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class GuildInviteIxCols
    {
        public global::SpacetimeDB.IxCol<GuildInvite, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GuildInvite, SpacetimeDB.Identity> InviteeId { get; }

        public GuildInviteIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GuildInvite, ulong>(tableName, "id");
            InviteeId = new global::SpacetimeDB.IxCol<GuildInvite, SpacetimeDB.Identity>(tableName, "invitee_id");
        }
    }
}
