// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GuildResourceTrackerHandle : RemoteTableHandle<EventContext, GuildResourceTracker>
        {
            protected override string RemoteTableName => "guild_resource_tracker";

            public sealed class GuildIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GuildResourceTracker row) => row.GuildId;

                public GuildIdIndex(GuildResourceTrackerHandle table) : base(table) { }
            }

            public readonly GuildIdIndex GuildId;

            public sealed class ByGuildAndResourceTypeIndex : BTreeIndexBase<(ulong GuildId, ResourceType Type)>
            {
                protected override (ulong GuildId, ResourceType Type) GetKey(GuildResourceTracker row) => (row.GuildId, row.Type);

                public ByGuildAndResourceTypeIndex(GuildResourceTrackerHandle table) : base(table) { }
            }

            public readonly ByGuildAndResourceTypeIndex ByGuildAndResourceType;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GuildResourceTracker row) => row.Id;

                public IdUniqueIndex(GuildResourceTrackerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GuildResourceTrackerHandle(DbConnection conn) : base(conn)
            {
                GuildId = new(this);
                ByGuildAndResourceType = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(GuildResourceTracker row) => row.Id;
        }

        public readonly GuildResourceTrackerHandle GuildResourceTracker;
    }

    public sealed class GuildResourceTrackerCols
    {
        public global::SpacetimeDB.Col<GuildResourceTracker, ulong> Id { get; }
        public global::SpacetimeDB.Col<GuildResourceTracker, ulong> GuildId { get; }
        public global::SpacetimeDB.Col<GuildResourceTracker, ResourceType> Type { get; }
        public global::SpacetimeDB.Col<GuildResourceTracker, ulong> Amount { get; }

        public GuildResourceTrackerCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GuildResourceTracker, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.Col<GuildResourceTracker, ulong>(tableName, "guild_id");
            Type = new global::SpacetimeDB.Col<GuildResourceTracker, ResourceType>(tableName, "type");
            Amount = new global::SpacetimeDB.Col<GuildResourceTracker, ulong>(tableName, "amount");
        }
    }

    public sealed class GuildResourceTrackerIxCols
    {
        public global::SpacetimeDB.IxCol<GuildResourceTracker, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GuildResourceTracker, ulong> GuildId { get; }
        public global::SpacetimeDB.IxCol<GuildResourceTracker, ResourceType> Type { get; }

        public GuildResourceTrackerIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GuildResourceTracker, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.IxCol<GuildResourceTracker, ulong>(tableName, "guild_id");
            Type = new global::SpacetimeDB.IxCol<GuildResourceTracker, ResourceType>(tableName, "type");
        }
    }
}
