// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GuildJoinRequestHandle : RemoteTableHandle<EventContext, GuildJoinRequest>
        {
            protected override string RemoteTableName => "guild_join_request";

            public sealed class GuildIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GuildJoinRequest row) => row.GuildId;

                public GuildIdIndex(GuildJoinRequestHandle table) : base(table) { }
            }

            public readonly GuildIdIndex GuildId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GuildJoinRequest row) => row.Id;

                public IdUniqueIndex(GuildJoinRequestHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RequesterIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(GuildJoinRequest row) => row.RequesterId;

                public RequesterIdUniqueIndex(GuildJoinRequestHandle table) : base(table) { }
            }

            public readonly RequesterIdUniqueIndex RequesterId;

            internal GuildJoinRequestHandle(DbConnection conn) : base(conn)
            {
                GuildId = new(this);
                Id = new(this);
                RequesterId = new(this);
            }

            protected override object GetPrimaryKey(GuildJoinRequest row) => row.Id;
        }

        public readonly GuildJoinRequestHandle GuildJoinRequest;
    }

    public sealed class GuildJoinRequestCols
    {
        public global::SpacetimeDB.Col<GuildJoinRequest, ulong> Id { get; }
        public global::SpacetimeDB.Col<GuildJoinRequest, ulong> GuildId { get; }
        public global::SpacetimeDB.Col<GuildJoinRequest, SpacetimeDB.Identity> RequesterId { get; }
        public global::SpacetimeDB.Col<GuildJoinRequest, SpacetimeDB.Timestamp> CreatedAt { get; }

        public GuildJoinRequestCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GuildJoinRequest, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.Col<GuildJoinRequest, ulong>(tableName, "guild_id");
            RequesterId = new global::SpacetimeDB.Col<GuildJoinRequest, SpacetimeDB.Identity>(tableName, "requester_id");
            CreatedAt = new global::SpacetimeDB.Col<GuildJoinRequest, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class GuildJoinRequestIxCols
    {
        public global::SpacetimeDB.IxCol<GuildJoinRequest, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GuildJoinRequest, ulong> GuildId { get; }
        public global::SpacetimeDB.IxCol<GuildJoinRequest, SpacetimeDB.Identity> RequesterId { get; }

        public GuildJoinRequestIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GuildJoinRequest, ulong>(tableName, "id");
            GuildId = new global::SpacetimeDB.IxCol<GuildJoinRequest, ulong>(tableName, "guild_id");
            RequesterId = new global::SpacetimeDB.IxCol<GuildJoinRequest, SpacetimeDB.Identity>(tableName, "requester_id");
        }
    }
}
