// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerShelterHandle : RemoteTableHandle<EventContext, PlayerShelter>
        {
            protected override string RemoteTableName => "player_shelter";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerShelter row) => row.Owner;

                public OwnerUniqueIndex(PlayerShelterHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            internal PlayerShelterHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerShelter row) => row.Owner;
        }

        public readonly PlayerShelterHandle PlayerShelter;
    }

    public sealed class PlayerShelterCols
    {
        public global::SpacetimeDB.Col<PlayerShelter, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerShelter, byte> Level { get; }
        public global::SpacetimeDB.Col<PlayerShelter, SpacetimeDB.Timestamp> BuiltAt { get; }

        public PlayerShelterCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<PlayerShelter, SpacetimeDB.Identity>(tableName, "owner");
            Level = new global::SpacetimeDB.Col<PlayerShelter, byte>(tableName, "level");
            BuiltAt = new global::SpacetimeDB.Col<PlayerShelter, SpacetimeDB.Timestamp>(tableName, "built_at");
        }
    }

    public sealed class PlayerShelterIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerShelter, SpacetimeDB.Identity> Owner { get; }

        public PlayerShelterIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<PlayerShelter, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
