// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerStructureHandle : RemoteTableHandle<EventContext, PlayerStructure>
        {
            protected override string RemoteTableName => "player_structure";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerStructure row) => row.Id;

                public IdUniqueIndex(PlayerStructureHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByOwnerAndDefinitionIndex : BTreeIndexBase<(SpacetimeDB.Identity Owner, ulong DefinitionId)>
            {
                protected override (SpacetimeDB.Identity Owner, ulong DefinitionId) GetKey(PlayerStructure row) => (row.Owner, row.DefinitionId);

                public ByOwnerAndDefinitionIndex(PlayerStructureHandle table) : base(table) { }
            }

            public readonly ByOwnerAndDefinitionIndex ByOwnerAndDefinition;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerStructure row) => row.Owner;

                public OwnerIndex(PlayerStructureHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal PlayerStructureHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByOwnerAndDefinition = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerStructure row) => row.Id;
        }

        public readonly PlayerStructureHandle PlayerStructure;
    }

    public sealed class PlayerStructureCols
    {
        public global::SpacetimeDB.Col<PlayerStructure, ulong> Id { get; }
        public global::SpacetimeDB.Col<PlayerStructure, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerStructure, ulong> DefinitionId { get; }
        public global::SpacetimeDB.Col<PlayerStructure, uint> Level { get; }
        public global::SpacetimeDB.Col<PlayerStructure, SpacetimeDB.Timestamp> BuiltAt { get; }

        public PlayerStructureCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerStructure, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<PlayerStructure, SpacetimeDB.Identity>(tableName, "owner");
            DefinitionId = new global::SpacetimeDB.Col<PlayerStructure, ulong>(tableName, "definition_id");
            Level = new global::SpacetimeDB.Col<PlayerStructure, uint>(tableName, "level");
            BuiltAt = new global::SpacetimeDB.Col<PlayerStructure, SpacetimeDB.Timestamp>(tableName, "built_at");
        }
    }

    public sealed class PlayerStructureIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStructure, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerStructure, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<PlayerStructure, ulong> DefinitionId { get; }

        public PlayerStructureIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerStructure, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<PlayerStructure, SpacetimeDB.Identity>(tableName, "owner");
            DefinitionId = new global::SpacetimeDB.IxCol<PlayerStructure, ulong>(tableName, "definition_id");
        }
    }
}
