// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerStatHandle : RemoteTableHandle<EventContext, PlayerStat>
        {
            protected override string RemoteTableName => "player_stat";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerStat row) => row.Id;

                public IdUniqueIndex(PlayerStatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerStat row) => row.Owner;

                public OwnerIndex(PlayerStatHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            public sealed class ByStatOwnerStatIndex : BTreeIndexBase<(SpacetimeDB.Identity Owner, StatType Stat)>
            {
                protected override (SpacetimeDB.Identity Owner, StatType Stat) GetKey(PlayerStat row) => (row.Owner, row.Stat);

                public ByStatOwnerStatIndex(PlayerStatHandle table) : base(table) { }
            }

            public readonly ByStatOwnerStatIndex ByStatOwnerStat;

            internal PlayerStatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Owner = new(this);
                ByStatOwnerStat = new(this);
            }

            protected override object GetPrimaryKey(PlayerStat row) => row.Id;
        }

        public readonly PlayerStatHandle PlayerStat;
    }

    public sealed class PlayerStatCols
    {
        public global::SpacetimeDB.Col<PlayerStat, ulong> Id { get; }
        public global::SpacetimeDB.Col<PlayerStat, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerStat, StatType> Stat { get; }
        public global::SpacetimeDB.Col<PlayerStat, int> Value { get; }

        public PlayerStatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlayerStat, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<PlayerStat, SpacetimeDB.Identity>(tableName, "owner");
            Stat = new global::SpacetimeDB.Col<PlayerStat, StatType>(tableName, "stat");
            Value = new global::SpacetimeDB.Col<PlayerStat, int>(tableName, "value");
        }
    }

    public sealed class PlayerStatIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStat, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PlayerStat, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<PlayerStat, StatType> Stat { get; }

        public PlayerStatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlayerStat, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<PlayerStat, SpacetimeDB.Identity>(tableName, "owner");
            Stat = new global::SpacetimeDB.IxCol<PlayerStat, StatType>(tableName, "stat");
        }
    }
}
