// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceTrackerHandle : RemoteTableHandle<EventContext, ResourceTracker>
        {
            protected override string RemoteTableName => "resource_tracker";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ResourceTracker row) => row.Id;

                public IdUniqueIndex(ResourceTrackerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ResourceTracker row) => row.Owner;

                public OwnerIndex(ResourceTrackerHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            public sealed class ByOwnerAndTypeIndex : BTreeIndexBase<(SpacetimeDB.Identity Owner, ResourceType Type)>
            {
                protected override (SpacetimeDB.Identity Owner, ResourceType Type) GetKey(ResourceTracker row) => (row.Owner, row.Type);

                public ByOwnerAndTypeIndex(ResourceTrackerHandle table) : base(table) { }
            }

            public readonly ByOwnerAndTypeIndex ByOwnerAndType;

            internal ResourceTrackerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Owner = new(this);
                ByOwnerAndType = new(this);
            }

            protected override object GetPrimaryKey(ResourceTracker row) => row.Id;
        }

        public readonly ResourceTrackerHandle ResourceTracker;
    }

    public sealed class ResourceTrackerCols
    {
        public global::SpacetimeDB.Col<ResourceTracker, ulong> Id { get; }
        public global::SpacetimeDB.Col<ResourceTracker, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<ResourceTracker, ResourceType> Type { get; }
        public global::SpacetimeDB.Col<ResourceTracker, ulong> Amount { get; }

        public ResourceTrackerCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ResourceTracker, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<ResourceTracker, SpacetimeDB.Identity>(tableName, "owner");
            Type = new global::SpacetimeDB.Col<ResourceTracker, ResourceType>(tableName, "type");
            Amount = new global::SpacetimeDB.Col<ResourceTracker, ulong>(tableName, "amount");
        }
    }

    public sealed class ResourceTrackerIxCols
    {
        public global::SpacetimeDB.IxCol<ResourceTracker, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ResourceTracker, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<ResourceTracker, ResourceType> Type { get; }

        public ResourceTrackerIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ResourceTracker, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<ResourceTracker, SpacetimeDB.Identity>(tableName, "owner");
            Type = new global::SpacetimeDB.IxCol<ResourceTracker, ResourceType>(tableName, "type");
        }
    }
}
