// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StructureDefinitionHandle : RemoteTableHandle<EventContext, StructureDefinition>
        {
            protected override string RemoteTableName => "structure_definition";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StructureDefinition row) => row.Id;

                public IdUniqueIndex(StructureDefinitionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(StructureDefinition row) => row.Name;

                public NameUniqueIndex(StructureDefinitionHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal StructureDefinitionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(StructureDefinition row) => row.Id;
        }

        public readonly StructureDefinitionHandle StructureDefinition;
    }

    public sealed class StructureDefinitionCols
    {
        public global::SpacetimeDB.Col<StructureDefinition, ulong> Id { get; }
        public global::SpacetimeDB.Col<StructureDefinition, string> Name { get; }
        public global::SpacetimeDB.Col<StructureDefinition, System.Collections.Generic.List<ActivityCost>> Cost { get; }

        public StructureDefinitionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<StructureDefinition, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<StructureDefinition, string>(tableName, "name");
            Cost = new global::SpacetimeDB.Col<StructureDefinition, System.Collections.Generic.List<ActivityCost>>(tableName, "cost");
        }
    }

    public sealed class StructureDefinitionIxCols
    {
        public global::SpacetimeDB.IxCol<StructureDefinition, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<StructureDefinition, string> Name { get; }

        public StructureDefinitionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<StructureDefinition, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.IxCol<StructureDefinition, string>(tableName, "name");
        }
    }
}
