// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StructureModifierHandle : RemoteTableHandle<EventContext, StructureModifier>
        {
            protected override string RemoteTableName => "structure_modifier";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StructureModifier row) => row.Id;

                public IdUniqueIndex(StructureModifierHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerStructureIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(StructureModifier row) => row.PlayerStructureId;

                public PlayerStructureIdIndex(StructureModifierHandle table) : base(table) { }
            }

            public readonly PlayerStructureIdIndex PlayerStructureId;

            internal StructureModifierHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerStructureId = new(this);
            }

            protected override object GetPrimaryKey(StructureModifier row) => row.Id;
        }

        public readonly StructureModifierHandle StructureModifier;
    }

    public sealed class StructureModifierCols
    {
        public global::SpacetimeDB.Col<StructureModifier, ulong> Id { get; }
        public global::SpacetimeDB.Col<StructureModifier, ulong> PlayerStructureId { get; }
        public global::SpacetimeDB.Col<StructureModifier, string> ModifierName { get; }
        public global::SpacetimeDB.Col<StructureModifier, int> Value { get; }

        public StructureModifierCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<StructureModifier, ulong>(tableName, "id");
            PlayerStructureId = new global::SpacetimeDB.Col<StructureModifier, ulong>(tableName, "player_structure_id");
            ModifierName = new global::SpacetimeDB.Col<StructureModifier, string>(tableName, "modifier_name");
            Value = new global::SpacetimeDB.Col<StructureModifier, int>(tableName, "value");
        }
    }

    public sealed class StructureModifierIxCols
    {
        public global::SpacetimeDB.IxCol<StructureModifier, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<StructureModifier, ulong> PlayerStructureId { get; }

        public StructureModifierIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<StructureModifier, ulong>(tableName, "id");
            PlayerStructureId = new global::SpacetimeDB.IxCol<StructureModifier, ulong>(tableName, "player_structure_id");
        }
    }
}
